version: "3.9"
services:
  postgres:
    image: postgres:13-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"

  xerum:
    build:
      context: .
      target: dev
    depends_on:
      - "postgres"
    volumes:
      - ./xerum:/app/xerum
      - ./tests:/app/tests
      - ./resources:/app/resources
    ports:
      - "5000:5000"
